version: 2
jobs:
  build:
    working_directory: ~/stock

    docker:
      - image: circleci/node:8-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: xvfb-run -a npm run test-ci
      - run: xvfb-run -a npm run e2e-ci

      - store_test_results:
          path: reports-metadata

      - store_artifacts:
          path: reports-metadata

  deploy:
    machine:
      enabled: true
    working_directory: ~/stock
    steps:
      - checkout
      - run: npm install -g now
      - run: npm install
      - run: npm run build
      - run: now -t ${NOW_TOKEN} --docker --public
      - run: now -t ${NOW_TOKEN} alias stock

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
